// lib/screens/pdf/pdf_viewer_screen.dart
// ✅ WITH EDIT CONSULTATION BUTTON

import 'package:flutter/material.dart';
import 'package:printing/printing.dart';
import 'dart:io';
import 'dart:typed_data';
import 'package:share_plus/share_plus.dart';
import 'package:path_provider/path_provider.dart';

class PDFViewerScreen extends StatelessWidget {
  final String pdfPath;
  final String title;
  final VoidCallback? onEditPressed; // ✅ NEW: Edit callback

  const PDFViewerScreen({
    super.key,
    required this.pdfPath,
    this.title = 'Consultation Report',
    this.onEditPressed, // ✅ NEW
  });

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
        backgroundColor: Colors.blue.shade700,
        foregroundColor: Colors.white,
        actions: [
          // ✅ NEW: Edit button
          if (onEditPressed != null)
            IconButton(
              icon: const Icon(Icons.edit),
              onPressed: onEditPressed,
              tooltip: 'Edit Consultation',
            ),
          IconButton(
            icon: const Icon(Icons.share),
            onPressed: () => _sharePDF(),
            tooltip: 'Share PDF',
          ),
          IconButton(
            icon: const Icon(Icons.print),
            onPressed: () => _printPDF(context),
            tooltip: 'Print PDF',
          ),
        ],
      ),
      body: PdfPreview(
        build: (format) => File(pdfPath).readAsBytes(),
        allowSharing: true,
        allowPrinting: true,
        canChangeOrientation: false,
        canChangePageFormat: false,
        canDebug: false,
        pdfFileName: title,
      ),
      bottomNavigationBar: _buildBottomBar(context),
    );
  }

  Widget _buildBottomBar(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: Colors.white,
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.1),
            blurRadius: 8,
            offset: const Offset(0, -2),
          ),
        ],
      ),
      child: SafeArea(
        top: false,
        child: Row(
          children: [
            // ✅ NEW: Edit button (if callback provided)
            if (onEditPressed != null) ...[
              Expanded(
                child: OutlinedButton.icon(
                  onPressed: onEditPressed,
                  icon: const Icon(Icons.edit),
                  label: const Text('Edit'),
                  style: OutlinedButton.styleFrom(
                    padding: const EdgeInsets.symmetric(vertical: 12),
                    foregroundColor: Colors.orange,
                    side: BorderSide(color: Colors.orange),
                  ),
                ),
              ),
              const SizedBox(width: 12),
            ],
            Expanded(
              child: OutlinedButton.icon(
                onPressed: () => _sharePDF(),
                icon: const Icon(Icons.share),
                label: const Text('Share'),
                style: OutlinedButton.styleFrom(
                  padding: const EdgeInsets.symmetric(vertical: 12),
                ),
              ),
            ),
            const SizedBox(width: 12),
            Expanded(
              child: ElevatedButton.icon(
                onPressed: () => _printPDF(context),
                icon: const Icon(Icons.print),
                label: const Text('Print'),
                style: ElevatedButton.styleFrom(
                  backgroundColor: Colors.blue.shade700,
                  foregroundColor: Colors.white,
                  padding: const EdgeInsets.symmetric(vertical: 12),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Future<void> _sharePDF() async {
    try {
      await Share.shareXFiles(
        [XFile(pdfPath)],
        subject: title,
        text: 'Consultation Report - Generated by Integrated Health App',
      );
    } catch (e) {
      print('Error sharing PDF: $e');
    }
  }

  Future<void> _printPDF(BuildContext context) async {
    try {
      final pdfBytes = await File(pdfPath).readAsBytes();
      await Printing.layoutPdf(
        onLayout: (format) async => pdfBytes,
        name: title,
      );
    } catch (e) {
      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error printing: $e'),
            backgroundColor: Colors.red,
          ),
        );
      }
    }
  }
}

// PDF viewer from bytes (unchanged)
class PDFViewerFromBytes extends StatelessWidget {
  final List<int> pdfBytes;
  final String title;

  const PDFViewerFromBytes({
    super.key,
    required this.pdfBytes,
    this.title = 'Consultation Report',
  });

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
        backgroundColor: Colors.blue.shade700,
        foregroundColor: Colors.white,
        actions: [
          IconButton(
            icon: const Icon(Icons.save),
            onPressed: () => _savePDF(context),
            tooltip: 'Save PDF',
          ),
          IconButton(
            icon: const Icon(Icons.share),
            onPressed: () => _sharePDF(context),
            tooltip: 'Share PDF',
          ),
        ],
      ),
      body: PdfPreview(
        build: (format) async => Uint8List.fromList(pdfBytes),
        allowSharing: true,
        allowPrinting: true,
        canChangeOrientation: false,
        canChangePageFormat: false,
        pdfFileName: title,
      ),
    );
  }

  Future<void> _savePDF(BuildContext context) async {
    try {
      final directory = await getApplicationDocumentsDirectory();
      final timestamp = DateTime.now().millisecondsSinceEpoch;
      final file = File('${directory.path}/consultation_$timestamp.pdf');
      await file.writeAsBytes(pdfBytes);

      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('PDF saved to ${file.path}'),
            backgroundColor: Colors.green,
            action: SnackBarAction(
              label: 'Open',
              textColor: Colors.white,
              onPressed: () {
                Navigator.push(
                  context,
                  MaterialPageRoute(
                    builder: (context) => PDFViewerScreen(pdfPath: file.path),
                  ),
                );
              },
            ),
          ),
        );
      }
    } catch (e) {
      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error saving PDF: $e'),
            backgroundColor: Colors.red,
          ),
        );
      }
    }
  }

  Future<void> _sharePDF(BuildContext context) async {
    try {
      final directory = await getTemporaryDirectory();
      final timestamp = DateTime.now().millisecondsSinceEpoch;
      final file = File('${directory.path}/consultation_$timestamp.pdf');
      await file.writeAsBytes(pdfBytes);

      await Share.shareXFiles(
        [XFile(file.path)],
        subject: title,
        text: 'Consultation Report',
      );
    } catch (e) {
      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error sharing PDF: $e'),
            backgroundColor: Colors.red,
          ),
        );
      }
    }
  }
}