// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9xYGd9TPau992ybHaQmbJqWkwyx4vlj8',
    appId: '1:683766033823:web:5f1e366f6c5288b99761aa',
    messagingSenderId: '683766033823',
    projectId: 'integrated-health-app-285e9',
    authDomain: 'integrated-health-app-285e9.firebaseapp.com',
    storageBucket: 'integrated-health-app-285e9.firebasestorage.app',
    measurementId: 'G-ZKQSKY7GVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh1BMhkGaV8zpysHzqO1MGhrHCxHXAOXI',
    appId: '1:683766033823:android:9d932b750e0a12cc9761aa',
    messagingSenderId: '683766033823',
    projectId: 'integrated-health-app-285e9',
    storageBucket: 'integrated-health-app-285e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXFElG0rkL8Gb-IpBB8S_uUy0Rx85D6ds',
    appId: '1:683766033823:ios:f90e1ba4461bd7de9761aa',
    messagingSenderId: '683766033823',
    projectId: 'integrated-health-app-285e9',
    storageBucket: 'integrated-health-app-285e9.firebasestorage.app',
    iosBundleId: 'com.example.integratedHealthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXFElG0rkL8Gb-IpBB8S_uUy0Rx85D6ds',
    appId: '1:683766033823:ios:f90e1ba4461bd7de9761aa',
    messagingSenderId: '683766033823',
    projectId: 'integrated-health-app-285e9',
    storageBucket: 'integrated-health-app-285e9.firebasestorage.app',
    iosBundleId: 'com.example.integratedHealthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9xYGd9TPau992ybHaQmbJqWkwyx4vlj8',
    appId: '1:683766033823:web:0c8ebb13c28fa4369761aa',
    messagingSenderId: '683766033823',
    projectId: 'integrated-health-app-285e9',
    authDomain: 'integrated-health-app-285e9.firebaseapp.com',
    storageBucket: 'integrated-health-app-285e9.firebasestorage.app',
    measurementId: 'G-R30NLJMLQD',
  );
}
